### ISSUE TITLE
blog.skookum.com doesn't result in blog content

### ISSUE THREAD

**Issue by treefort** [Skookum/skookum.com#143]
Looks like `http://blog.skookum.com` just needs to redirect to `http://blog.skookum.com/blog`

**Comment by markflowers** [comment]
I didn't really think about this, its a DNS issue (a.k.a. my problem). Does it need to be `http://blog.skookum.com/blog` or `http://skookum.com/blog`?

**Comment by treefort** [comment]
I definitely prefer the latter. I assumed the 'proper' URL was `http://blog.skookum.com/blog` because I manually typed `http://blog.skookum.com` before clicking the (relative) link in the top nav.

Speaking of... I'd imagine we probably want to avoid this scenario as well: `http://holdontoyourbutts.skookum.com/capabilities`

**Comment by markflowers** [comment]
Just kidding, this is an `.htaccess` thing. @scpaye506 can you take a look at it when you get a chance?

**Comment by scpaye506** [comment]
updated with https://github.com/Skookum/skookum.com/pull/149
